---
title: 'Ecological case studies: Supplementary figures'
author: "Sandra Emry"
date: "2023-08-04"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(metafor)
library(emmeans)
library(tidyverse)
source("https://raw.githubusercontent.com/rnorouzian/i/master/3m.r")

model_full <- rma.mv(yi, vi, mods = ~ realm + impact + movement + larger_group, method = "ML", random = ~1|study_id, data = heatdome_ROM, dfs = "contain")
```

Forest plot for taxonomic group

```{r Taxonomic groupings}

post_rma(model_full, ~larger_group)
taxonomic_LRR <- post_rma(model_full, ~larger_group)$table %>% 
  mutate(across(Mean:`p-value`, ~as.numeric(.)))

heatdome_ROM %>% group_by(larger_group) %>% tally()

taxonomy_plot <- ggplot(data = taxonomic_LRR) + 
  geom_point(aes(x = larger_group, y = Mean)) + 
  geom_errorbar(aes(x = larger_group, ymin =Lower, ymax = Upper), linewidth = 0.4, width = 0.2) + 
  geom_hline(yintercept = 0, linetype = 2) + 
  scale_y_continuous(limits = c(-2.75, 1.25)) +
  scale_x_discrete(labels = c("plants" = "Plants (5)", "mammals" = "Mammals (14)", "invertebrates" = "Invertebrates (11)", "birds" = "Birds (15)")) + 
  coord_flip() + 
  theme_classic() + 
  labs(x = "Taxonomic groupings", y = "LRR")
```

```{r realm}

post_rma(model_full, ~realm)

realm_LRR <- post_rma(model_full, ~realm)$table %>% 
  mutate(across(Mean:`p-value`, ~as.numeric(.)))

heatdome_ROM %>% group_by(realm) %>% tally()

realm_plot <- ggplot(data = realm_LRR) + 
  geom_point(aes(x = realm, y = Mean)) + 
  geom_errorbar(aes(x = realm, ymin =Lower, ymax = Upper), linewidth = 0.4, width = 0.2) + 
  geom_hline(yintercept = 0, linetype = 2) + 
  scale_y_continuous(limits = c(-2.75, 1.25)) +
  scale_x_discrete(labels = c("marine" = "Marine (10)", "terrestrial" = "Terrestrial (35)")) + 
  coord_flip() + 
  theme_classic() + 
  labs(x = "Realm", y = "LRR")
```

```{r movement}

post_rma(model_full, ~movement)

movement_LRR <- post_rma(model_full, ~movement)$table %>% 
  mutate(across(Mean:`p-value`, ~as.numeric(.)))

heatdome_ROM %>% group_by(movement) %>% tally()

movement_plot <- ggplot(data = movement_LRR) + 
  geom_point(aes(x = movement, y = Mean)) + 
  geom_errorbar(aes(x = movement, ymin =Lower, ymax = Upper), linewidth = 0.4, width = 0.2) + 
  geom_hline(yintercept = 0, linetype = 2) + 
  scale_y_continuous(limits = c(-2.75, 1.25)) +
  scale_x_discrete(labels = c("sessile" = "Sessile (13)", "motile" = "Motile (32)")) + 
  coord_flip() + 
  theme_classic() + 
  labs(x = "Movement", y = "LRR")
```


```{r impact}

post_rma(model_full, ~impact)

impact_LRR <- post_rma(model_full, ~impact)$table %>% 
  mutate(across(Mean:`p-value`, ~as.numeric(.)))

heatdome_ROM %>% group_by(impact) %>% tally()

impact_plot <- ggplot(data = impact_LRR) + 
  geom_point(aes(x = impact, y = Mean)) + 
  geom_errorbar(aes(x = impact, ymin =Lower, ymax = Upper), linewidth = 0.4, width = 0.2) + 
  geom_hline(yintercept = 0, linetype = 2) + 
  scale_x_discrete(labels = c("after" = "After (30)", "during" = "During (15)")) + 
  scale_y_continuous(limits = c(-2.75, 1.25)) +
  coord_flip() + 
  theme_classic() + 
  labs(x = "Time frame", y = "LRR")
```

```{r join plots }

final_plot <- movement_plot + impact_plot + realm_plot + taxonomy_plot 

ggsave("./figures/case_study_plots_moderator_LRR.jpg", plot = final_plot)

```
